FROM mcr.microsoft.com/playwright/python:v1.56.0-noble

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1
ENV TZ=Asia/Seoul

WORKDIR /app

COPY requirements-naver.txt ./
RUN pip install --upgrade pip \
    && pip install -r requirements-naver.txt

COPY . .

CMD ["python", "scripts/scheduler_naver.py"]
